### ISSUE TITLE
Directional Light has no effect

### ISSUE THREAD

**Issue by mattdm** [ethereumdegen/bevy_mesh_terrain#9]
I assume this is related to #7 ... light (or lack thereof) from DirectionalLight doesn't do anything -- no brightness, and no shadows. The terrain is always constantly bright.

I haven't looked at other light sources yet but they're probably the same...

**Comment by ethereumdegen** [comment]
Yes, the terrain shader need to implement lighting as it currently does not 


>> It would be nice to be able to adjust some of these options. Particularly, normal maps — but maybe also reflectance, perceptual_roughness, etc.
